language: python

python: "3.7"
dist: xenial
sudo: required

before_install:
  - travis_retry pip install -U pip wheel setuptools

install:
  - travis_retry pip install --pre scaraplate


script:
  - rm -Rf generated_project
  - scaraplate rollup . generated_project --no-input
  - cd generated_project
  - make venv
  - |
    bash <<EOF
    source ./venv/bin/activate
    set -eux
    make develop
    make lint
    make test
    make format
    EOF
