language: python

python: "3.7"
dist: xenial
sudo: required

before_install:
  - travis_retry pip install -U pip wheel setuptools

install:
  - travis_retry pip install 'scaraplate>=0.2'

script:
  - make test
